// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BasicActiveObjectExample;

/************************************************************/
/**
 * 
 */
public class AIM_TmTc_Struct extends CAN_TmTc_Struct {
	/**
	 * 
	 */
	private int mtq_speed = 0;
	/**
	 * 
	 */
	private int mtm_value;
	/**
	 * 
	 */
	private int wheel_1_speed;
	/**
	 * 
	 */
	private int wheel_2_speed;

	/**
	 * 
	 */
	public void setMtq_speed() {
	}

	/**
	 * 
	 */
	public void setMtm_value() {
	}

	/**
	 * 
	 */
	public void setWheel_1_speed() {
	}

	/**
	 * 
	 */
	public void setWheel_2_speed() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getMtq_speed() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getMtm_value() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getWheel_1_speed() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getWheel_2_speed() {
	}
}
