// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BasicActiveObjectExample;

/************************************************************/
/**
 * 
 */
public class AOCS_Module {
	/**
	 * 
	 */
	public AIM_TmTc_Struct[] aim_tmtc_struct;
}
