// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BasicActiveObjectExample;

/************************************************************/
/**
 * 
 */
public class AOCS Initilisation {
}
