// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BasicActiveObjectExample;

/************************************************************/
/**
 * 
 */
public class ARO_CounterStatus {
}
