// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BasicActiveObjectExample;

/************************************************************/
/**
 * 
 */
public class CAN_TmTc_Struct {
	/**
	 * 
	 */
	public Integer destinationAddress = 255;
	/**
	 * 
	 */
	public Integer sourceAddress = 255;

	/**
	 * 
	 * @param address 
	 */
	public void setDestinationAddress(int address) {
	}

	/**
	 * 
	 * @return 
	 */
	public int getDestinationAddress() {
		return this.destinationAddress;
	}

	/**
	 * 
	 * @return 
	 */
	public int getSourceAddress() {
		return this.sourceAddress;
	}

	/**
	 * 
	 * @param address 
	 */
	public void setSourceAddress(int address) {
	}
}
