// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BasicActiveObjectExample;

import java.util.concurrent.Semaphore;

/************************************************************/
/**
 * 
 */
public class PowerThread extends Thread {
	/**
	 * 
	 */
	public static Semaphore lock;
}
