// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BasicActiveObjectExample;

import java.util.List;

// Manual imports
import java.lang.Thread;
// End of manual imports

/************************************************************/
/**
 * 
 */
public class StateThread extends Thread {
	/**
	 * 
	 */
	private List pipeInputStream;
}
