// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package BasicActiveObjectExample;

/************************************************************/
/**
 * 
 */
public class State_Machine_AOCS {
	/**
	 * 
	 */
	public enum AlarmStates {
		/**
		 * 
		 */
		NO_ALARM,
		/**
		 * 
		 */
		WARNING,
		/**
		 * 
		 */
		ALARM;
	};

	/**
	 * 
	 */
	private PowerThread powerthread;
	/**
	 * 
	 */
	private StateThread statethread;
	/**
	 * 
	 */
	public static int aroCounter = 200;
	/**
	 * 
	 */
	public AlarmStates aocsAlarmState = AlarmStates.NO_ALARM;

	/**
	 * 
	 */
	public void setAOCSMode() {
	}

	/**
	 * 
	 */
	public void aroStateMachine() {
	}
}
